### ISSUE TITLE
news item on the hermes catalog

### ISSUE THREAD

**Issue by mrtommyb** [tessgi/TessGiWebsite#31]

**Comment by mrtommyb** [comment]
I'm assigning this to @elisaquintana as she is in the hotseat this week

**Comment by mrtommyb** [comment]
https://arxiv.org/abs/1707.05753

**Comment by mrtommyb** [comment]
You also might want to consider pointing users to the TESS-HERMES catalog for their GI proposals.
www.physics.usyd.edu.au/tess-hermes/
2017arXiv170705753S

**Comment by elisaquintana** [comment]
The TESS-HERMES catalog of spectroscopic stellar parameters is now available

A catalog of spectroscopic stellar parameters for stars in the TESS southern continuous viewing zone (CVZ) is now available and provides a valuable resource for TESS GI proposal preparation. Data taken by the High Efficiency and Resolution Multi-Element Spectrograph (HERMES) at the Anglo-Australian Telescope, as part of the TESS-HERMES survey, provides (Teff, logg, [Fe/H], vsini, vmicro) for about 16,000 dwarf and subgiant stars with magnitudes 10<V<13.1, along with Bayesian estimates of stellar properties (distance, extinction, mass, radius, and age) using theoretical isochrones. Stellar surface gravity and radius are made available for an additional set of roughly 8,500 red giants. The TESS-HERMES catalog has flagged over a hundred cool dwarfs that were flagged as giant stars in the TESS Input Catalog (TIC).

Details on the TESS-HERMES survey can be found [here](www.physics.usyd.edu.au/tess-hermes/), which provides links to the catalog (.csv and .fits) and tables describing the content of the catalogs.

The article describing the survey (Sharma et al. 2017) can be found [here](https://arxiv.org/abs/1707.05753).

We thank Dennis Stello, Sanjib Sharma, and the HERMES team for providing this information.

**Comment by elisaquintana** [comment]
^should I be more clear about what vsini and vmicro (etc.) is?

**Comment by elisaquintana** [comment]
First link is broken, I think, should be:
http://www.physics.usyd.edu.au/tess-hermes/

**Comment by elisaquintana** [comment]
Second link should be:
https://arxiv.org/abs/1707.05753

**Comment by mrtommyb** [comment]
Ok, I'll edit a little

**Comment by mrtommyb** [comment]
The TESS-HERMES catalog of spectroscopic stellar parameters is now available

A catalog of spectroscopic stellar parameters for stars in the TESS southern continuous viewing zone (CVZ) is now available and may prove a useful resource for [TESS GI proposal preparation](proposing-investigations.html). Data taken by the High Efficiency and Resolution Multi-Element Spectrograph (HERMES) at the Anglo-Australian Telescope, as part of the TESS-HERMES survey, provides temperate, surface gravity, and metalicity for about 16,000 dwarf and subgiant stars with magnitudes 10<V<13.1, along with Bayesian estimates of stellar properties (distance, extinction, mass, radius, and age) using theoretical isochrones. Stellar surface gravity and radius are made available for an additional set of roughly 8,500 red giants. The TESS-HERMES catalog has identified over a hundred cool dwarfs that were flagged as giant stars in the TESS Input Catalog (TIC).

The [TESS-HERMES survey website](www.physics.usyd.edu.au/tess-hermes/)  provides links to the catalog (.csv and .fits) and tables describing the content of the catalogs. While an article describing the survey (Sharma et al. 2017) can be found [on the arxiv](https://arxiv.org/abs/1707.05753).

We thank Sanjib Sharma, Dennis Stello, and the HERMES team for their hard work in making this resource available in time for GI Cycle 1.

**Comment by elisaquintana** [comment]
Use this (corrections):

The TESS-HERMES catalog of spectroscopic stellar parameters is now available

A catalog of spectroscopic stellar parameters for stars in the TESS southern continuous viewing zone (CVZ) is now available and provides a valuable resource for TESS GI proposal preparation. Data taken by the High Efficiency and Resolution Multi-Element Spectrograph (HERMES) at the Anglo-Australian Telescope, as part of the TESS-HERMES survey, provides fundamental stellar parameters for about 16,000 dwarf and subgiant stars with magnitudes 10<V<13.1. Specifically, the effective temperature (Teff), stellar surface gravity (log g), metallicity ([Fe/H]) and rotational velocity (vsini) are provided, along with Bayesian estimates of distance, extinction, mass, radius, and age using theoretical isochrones. Stellar surface gravity and radius are made available for an additional set of roughly 8,500 red giants. The TESS-HERMES catalog has flagged over a hundred cool dwarfs that were flagged as giants in the TESS Input Catalog (TIC).

Details on the TESS-HERMES survey can be found [here](www.physics.usyd.edu.au/tess-hermes/), which provides links to the catalog (.csv and .fits) and tables describing the content of the catalogs.

The article describing the survey (Sharma et al. 2017) can be found [here](https://arxiv.org/abs/1707.05753).

Acknowledgement to Dennis Stello, Sanjib Sharma, and the HERMES team for providing this information.

**Comment by mrtommyb** [comment]
ok, I pushed the changes
