### ISSUE TITLE
404 link on  TessGiWebsite/content/pages/data-analysis/software.md

### ISSUE THREAD

**Issue by texadactyl** [tessgi/TessGiWebsite#35]
On the above referenced page,
proposal tools page, ticgen, and tvguide all ==> 404

**Comment by mrtommyb** [comment]
Could you give the URL that these link to on the dev or live site? I wasn't able to reproduce the 404 on there.

**Comment by texadactyl** [comment]
Sure.  I was just browsing this site and stumbled over those links.  Peace.

**Comment by mrtommyb** [comment]
It looks like those links are working on http://tessgi.github.io/TessGiWebsite/.
This looks like it's only a issue when you browse the markdown on github.
